### ISSUE TITLE
Upload additional files of the course.

### ISSUE THREAD

**Issue by Skywalker97** [Karamya/OpenCV#1]
There are several files (images mainly) which you are using in the code. Please upload them.

**Comment by pablodz** [comment]
x2

**Comment by Karamya** [comment]
Will do it within the next day

**Comment by pablodz** [comment]
Thanks, I already found this one:
` https://www.superdatascience.com/deep-learning/`

**Comment by Karamya** [comment]
> Thanks, I already found this one:
> `https://www.superdatascience.com/deep-learning/`

Thanks for the link. Seems interesting

**Comment by Karamya** [comment]
Uploaded the relevant files
